config/routes.rb
Rails.application.routes.draw do
  resources :globals
  root 'globals#index'

end

app/models/global.rb
class Global < ActiveRecord::Base
  serialize :value
  validates :key,
    :presence => {:message => "Key is required"},
    :uniqueness => {:message => "Key already exists"},
    :length => {:minimum => 2, :message => "Key should at least be 2 characters long"}

  before_save  :confirm_value_type
  after_commit :flush_cache

  def confirm_value_type
    if self.is_b?
      self.value = self.value.present?
    elsif self.is_i?
      self.value = self.value.to_i
    elsif self.is_f?
      self.value = self.value.to_f
    else
      self.value = self.value.to_s
    end
    true
  end

  def is_i?
    return false if self.value.blank?
    !!(self.value.to_s =~ /\A[-+]?[0-9]+\z/)
  end

  def is_f?
    return false if self.value.blank?
    !!(self.value.to_s =~ /^\s*[+-]?((\d+_?)*\d+(\.(\d+_?)*\d+)?|\.(\d+_?)*\d+)(\s*)$/)
  end

  def is_b?
    !!(self.key.to_s =~ /.*\?\z/)
  end

  def type_name
    case self.value.class.name
    when "Fixnum"
      "Integer"
    when "Float"
      "Float"
    when "TrueClass", "FalseClass"
      "Boolean"
    when "String"
      "String"
    else
      "NotAllowed"
    end
  end

  def self.find_from_cache id
    Rails.cache.fetch(["global", id]) { find_by_id id }
  end

  def flush_cache
    Rails.cache.delete(["global", id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/globals_controller.rb
class GlobalsController < ApplicationController
  def index
    @globals = Global.paginate :per_page => 25, :page => params[:page]
  end

  def new
    @global = Global.new
  end

  def edit
    @global = Global.find_from_cache params[:id]
    @global.value = nil if @global.is_b? && !@global.value
  end

  def create
    @global = Global.new global_params
    if @global.save
      flash[:notice] = "Global created successfully"
      return redirect_to(globals_path)
    else
      flash[:error] = @global.errors.messages.values.join("<br />")
      return render(:action => :new)
    end
  end

  def update
    @global = Global.find_from_cache params[:id]
    if @global.update_attributes global_params
      flash[:notice] = "Global saved successfully"
      return redirect_to(globals_path)
    else
      flash[:error] = @global.errors.messages.values.join("<br />")
      return render(:action => :edit)
    end
  end

  def destroy
    @global = Global.find_from_cache params[:id]
    if @global.destroy
      flash[:notice] = "Global deleted successfully"
    else
      flash[:notice] = "Global could not be deleted"
    end
    return redirect_to(globals_path)
  end

  private

  def global_params
    return params.require(:global).permit(:key, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/globals_helper.rb
module GlobalsHelper
end

app/views/globals/_form.html.erb
<div class="control-group">
  <%= form.label :key, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :key %>
    <p class="help-block">For boolean type globals, postfix the key with a '?'</p>
  </div>
</div>

<div class="control-group">
  <%= form.label :value, :class => "control-label" %>
  <div class="controls">
    <%= form.text_field :value %>
  </div>
</div>

<div class="form-actions">
  <%= form.submit :class => "btn btn-primary" %>
</div>

app/views/globals/edit.html.erb
<div class="row-fluid">
  <div class="span6 well">
    <%= form_for @global, :url => global_path(@global.id), :html => {:class => "form-horizontal"} do |form| %>
      <fieldset>
        <legend>Edit Global</legend>
        <%= render :partial => 'form', :locals => {:form => form} %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/globals/index.html.erb
<div class="row">
  <div class="table">
    <table class="table-bordered table-striped">
      <thead>
        <tr>
          <th>
            Key
          </th>
          <th>
            Value
          </th>
          <th>
            Type
          </th>
          <th>
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <% @globals.each do |g| %>
          <tr>
            <td>
              <%= g.key %>
            </td>
            <td>
              <%= g.value %>
            </td>
            <td>
              <%= g.type_name %>
            </td>
            <td>
              <%= link_to "Edit", edit_global_path(g.id) %> <%= link_to "Delete", global_path(g.id), :method => 'DELETE' %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td colspan="4">
            <%= link_to 'New Global', new_global_path %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <%= will_paginate @globals %>
</div>

app/views/globals/new.html.erb
<div class="row-fluid">
  <div class="span6 well">
    <%= form_for @global, :url => globals_path, :html => {:class => "form-horizontal"} do |form| %>
      <fieldset>
        <legend>New Global</legend>
        <%= render :partial => 'form', :locals => {:form => form} %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stelladot" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Stelladot</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Globals", globals_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Globals", globals_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <% flash.each do |name, msg| %>
            <div class='alert alert-<%= name == 'notice' ? "success" : "error" %>'>
              <a class="close" data-dismiss="alert">×</a>
              <%= raw msg %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>